/*
 * Generated by gdbus-codegen 2.32.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "ganymed-bindings.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.manuel.Ganymed
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:Ganymed
 * @title: Ganymed
 * @short_description: Generated C code for the org.manuel.Ganymed D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.manuel.Ganymed ---- */

static const _ExtendedGDBusArgInfo _ganymed_method_info_connect_IN_ARG_remote_public_key =
{
  {
    -1,
    "remote_public_key",
    "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_connect_IN_ARG_port =
{
  {
    -1,
    "port",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_connect_IN_ARG_timeout =
{
  {
    -1,
    "timeout",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ganymed_method_info_connect_IN_ARG_pointers[] =
{
  &_ganymed_method_info_connect_IN_ARG_remote_public_key,
  &_ganymed_method_info_connect_IN_ARG_port,
  &_ganymed_method_info_connect_IN_ARG_timeout,
  NULL
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_connect_OUT_ARG_fd =
{
  {
    -1,
    "fd",
    "h",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ganymed_method_info_connect_OUT_ARG_pointers[] =
{
  &_ganymed_method_info_connect_OUT_ARG_fd,
  NULL
};

static const _ExtendedGDBusMethodInfo _ganymed_method_info_connect =
{
  {
    -1,
    "connect",
    (GDBusArgInfo **) &_ganymed_method_info_connect_IN_ARG_pointers,
    (GDBusArgInfo **) &_ganymed_method_info_connect_OUT_ARG_pointers,
    NULL
  },
  "handle-connect",
  TRUE
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_add_node_IN_ARG_node_name =
{
  {
    -1,
    "node_name",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_add_node_IN_ARG_remote_public_key =
{
  {
    -1,
    "remote_public_key",
    "ay",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ganymed_method_info_add_node_IN_ARG_pointers[] =
{
  &_ganymed_method_info_add_node_IN_ARG_node_name,
  &_ganymed_method_info_add_node_IN_ARG_remote_public_key,
  NULL
};

static const _ExtendedGDBusMethodInfo _ganymed_method_info_add_node =
{
  {
    -1,
    "add_node",
    (GDBusArgInfo **) &_ganymed_method_info_add_node_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-add-node",
  FALSE
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_find_node_IN_ARG_keywords =
{
  {
    -1,
    "keywords",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ganymed_method_info_find_node_IN_ARG_pointers[] =
{
  &_ganymed_method_info_find_node_IN_ARG_keywords,
  NULL
};

static const _ExtendedGDBusArgInfo _ganymed_method_info_find_node_OUT_ARG_nodes =
{
  {
    -1,
    "nodes",
    "aay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo * const _ganymed_method_info_find_node_OUT_ARG_pointers[] =
{
  &_ganymed_method_info_find_node_OUT_ARG_nodes,
  NULL
};

static const _ExtendedGDBusMethodInfo _ganymed_method_info_find_node =
{
  {
    -1,
    "find_node",
    (GDBusArgInfo **) &_ganymed_method_info_find_node_IN_ARG_pointers,
    (GDBusArgInfo **) &_ganymed_method_info_find_node_OUT_ARG_pointers,
    NULL
  },
  "handle-find-node",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _ganymed_method_info_pointers[] =
{
  &_ganymed_method_info_connect,
  &_ganymed_method_info_add_node,
  &_ganymed_method_info_find_node,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _ganymed_interface_info =
{
  {
    -1,
    "org.manuel.Ganymed",
    (GDBusMethodInfo **) &_ganymed_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "ganymed",
};


/**
 * ganymed_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
ganymed_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_ganymed_interface_info;
}

/**
 * ganymed_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #Ganymed interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
ganymed_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * Ganymed:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link>.
 */

/**
 * GanymedIface:
 * @parent_iface: The parent interface.
 * @handle_add_node: Handler for the #Ganymed::handle-add-node signal.
 * @handle_connect: Handler for the #Ganymed::handle-connect signal.
 * @handle_find_node: Handler for the #Ganymed::handle-find-node signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link>.
 */

static void
ganymed_default_init (GanymedIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * Ganymed::handle-connect:
   * @object: A #Ganymed.
   * @invocation: A #GDBusMethodInvocation.
   * @fd_list: (allow-none): A #GUnixFDList or %NULL.
   * @arg_remote_public_key: Argument passed by remote caller.
   * @arg_port: Argument passed by remote caller.
   * @arg_timeout: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-manuel-Ganymed.connect">connect()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ganymed_complete_connect() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-connect",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GanymedIface, handle_connect),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UNIX_FD_LIST, G_TYPE_VARIANT, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * Ganymed::handle-add-node:
   * @object: A #Ganymed.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_node_name: Argument passed by remote caller.
   * @arg_remote_public_key: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-manuel-Ganymed.add_node">add_node()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ganymed_complete_add_node() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add-node",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GanymedIface, handle_add_node),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRV, G_TYPE_STRING);

  /**
   * Ganymed::handle-find-node:
   * @object: A #Ganymed.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_keywords: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-manuel-Ganymed.find_node">find_node()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ganymed_complete_find_node() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-find-node",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GanymedIface, handle_find_node),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRV);

}

typedef GanymedIface GanymedInterface;
G_DEFINE_INTERFACE (Ganymed, ganymed, G_TYPE_OBJECT);

/**
 * ganymed_call_connect:
 * @proxy: A #GanymedProxy.
 * @arg_remote_public_key: Argument to pass with the method invocation.
 * @arg_port: Argument to pass with the method invocation.
 * @arg_timeout: Argument to pass with the method invocation.
 * @fd_list: (allow-none): A #GUnixFDList or %NULL.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-manuel-Ganymed.connect">connect()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ganymed_call_connect_finish() to get the result of the operation.
 *
 * See ganymed_call_connect_sync() for the synchronous, blocking version of this method.
 */
void
ganymed_call_connect (
    Ganymed *proxy,
    GVariant *arg_remote_public_key,
    guint arg_port,
    guint arg_timeout,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call_with_unix_fd_list (G_DBUS_PROXY (proxy),
    "connect",
    g_variant_new ("(@ayuu)",
                   arg_remote_public_key,
                   arg_port,
                   arg_timeout),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    fd_list,
    cancellable,
    callback,
    user_data);
}

/**
 * ganymed_call_connect_finish:
 * @proxy: A #GanymedProxy.
 * @out_fd: (out): Return location for return parameter or %NULL to ignore.
 * @out_fd_list: (out): Return location for a #GUnixFDList or %NULL.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ganymed_call_connect().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ganymed_call_connect().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ganymed_call_connect_finish (
    Ganymed *proxy,
    GVariant **out_fd,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_with_unix_fd_list_finish (G_DBUS_PROXY (proxy), out_fd_list, res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@h)",
                 out_fd);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ganymed_call_connect_sync:
 * @proxy: A #GanymedProxy.
 * @arg_remote_public_key: Argument to pass with the method invocation.
 * @arg_port: Argument to pass with the method invocation.
 * @arg_timeout: Argument to pass with the method invocation.
 * @fd_list: (allow-none): A #GUnixFDList or %NULL.
 * @out_fd: (out): Return location for return parameter or %NULL to ignore.
 * @out_fd_list: (out): Return location for a #GUnixFDList or %NULL.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-manuel-Ganymed.connect">connect()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ganymed_call_connect() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ganymed_call_connect_sync (
    Ganymed *proxy,
    GVariant *arg_remote_public_key,
    guint arg_port,
    guint arg_timeout,
    GUnixFDList  *fd_list,
    GVariant **out_fd,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_with_unix_fd_list_sync (G_DBUS_PROXY (proxy),
    "connect",
    g_variant_new ("(@ayuu)",
                   arg_remote_public_key,
                   arg_port,
                   arg_timeout),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    fd_list,
    out_fd_list,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@h)",
                 out_fd);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ganymed_call_add_node:
 * @proxy: A #GanymedProxy.
 * @arg_node_name: Argument to pass with the method invocation.
 * @arg_remote_public_key: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-manuel-Ganymed.add_node">add_node()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ganymed_call_add_node_finish() to get the result of the operation.
 *
 * See ganymed_call_add_node_sync() for the synchronous, blocking version of this method.
 */
void
ganymed_call_add_node (
    Ganymed *proxy,
    const gchar *const *arg_node_name,
    const gchar *arg_remote_public_key,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "add_node",
    g_variant_new ("(^as^ay)",
                   arg_node_name,
                   arg_remote_public_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ganymed_call_add_node_finish:
 * @proxy: A #GanymedProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ganymed_call_add_node().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ganymed_call_add_node().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ganymed_call_add_node_finish (
    Ganymed *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ganymed_call_add_node_sync:
 * @proxy: A #GanymedProxy.
 * @arg_node_name: Argument to pass with the method invocation.
 * @arg_remote_public_key: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-manuel-Ganymed.add_node">add_node()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ganymed_call_add_node() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ganymed_call_add_node_sync (
    Ganymed *proxy,
    const gchar *const *arg_node_name,
    const gchar *arg_remote_public_key,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "add_node",
    g_variant_new ("(^as^ay)",
                   arg_node_name,
                   arg_remote_public_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ganymed_call_find_node:
 * @proxy: A #GanymedProxy.
 * @arg_keywords: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-manuel-Ganymed.find_node">find_node()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ganymed_call_find_node_finish() to get the result of the operation.
 *
 * See ganymed_call_find_node_sync() for the synchronous, blocking version of this method.
 */
void
ganymed_call_find_node (
    Ganymed *proxy,
    const gchar *const *arg_keywords,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "find_node",
    g_variant_new ("(^as)",
                   arg_keywords),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ganymed_call_find_node_finish:
 * @proxy: A #GanymedProxy.
 * @out_nodes: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ganymed_call_find_node().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ganymed_call_find_node().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ganymed_call_find_node_finish (
    Ganymed *proxy,
    GVariant **out_nodes,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aay)",
                 out_nodes);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ganymed_call_find_node_sync:
 * @proxy: A #GanymedProxy.
 * @arg_keywords: Argument to pass with the method invocation.
 * @out_nodes: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-manuel-Ganymed.find_node">find_node()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ganymed_call_find_node() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ganymed_call_find_node_sync (
    Ganymed *proxy,
    const gchar *const *arg_keywords,
    GVariant **out_nodes,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "find_node",
    g_variant_new ("(^as)",
                   arg_keywords),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aay)",
                 out_nodes);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ganymed_complete_connect:
 * @object: A #Ganymed.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @fd_list: (allow-none): A #GUnixFDList or %NULL.
 * @fd: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-manuel-Ganymed.connect">connect()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ganymed_complete_connect (
    Ganymed *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *fd)
{
  g_dbus_method_invocation_return_value_with_unix_fd_list (invocation,
    g_variant_new ("(@h)",
                   fd),
    fd_list);
}

/**
 * ganymed_complete_add_node:
 * @object: A #Ganymed.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-manuel-Ganymed.add_node">add_node()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ganymed_complete_add_node (
    Ganymed *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * ganymed_complete_find_node:
 * @object: A #Ganymed.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @nodes: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-manuel-Ganymed.find_node">find_node()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ganymed_complete_find_node (
    Ganymed *object,
    GDBusMethodInvocation *invocation,
    GVariant *nodes)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@aay)",
                   nodes));
}

/* ------------------------------------------------------------------------ */

/**
 * GanymedProxy:
 *
 * The #GanymedProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GanymedProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GanymedProxy.
 */

struct _GanymedProxyPrivate
{
  GData *qdata;
};

static void ganymed_proxy_iface_init (GanymedIface *iface);

G_DEFINE_TYPE_WITH_CODE (GanymedProxy, ganymed_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_GANYMED, ganymed_proxy_iface_init));

static void
ganymed_proxy_finalize (GObject *object)
{
  GanymedProxy *proxy = GANYMED_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (ganymed_proxy_parent_class)->finalize (object);
}

static void
ganymed_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
ganymed_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
ganymed_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_ganymed_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_GANYMED);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_GANYMED);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
ganymed_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GanymedProxy *proxy = GANYMED_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ganymed_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ganymed_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
ganymed_proxy_init (GanymedProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_GANYMED_PROXY, GanymedProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), ganymed_interface_info ());
}

static void
ganymed_proxy_class_init (GanymedProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (GanymedProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = ganymed_proxy_finalize;
  gobject_class->get_property = ganymed_proxy_get_property;
  gobject_class->set_property = ganymed_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = ganymed_proxy_g_signal;
  proxy_class->g_properties_changed = ganymed_proxy_g_properties_changed;

}

static void
ganymed_proxy_iface_init (GanymedIface *iface)
{
}

/**
 * ganymed_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ganymed_proxy_new_finish() to get the result of the operation.
 *
 * See ganymed_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
ganymed_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_GANYMED_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.manuel.Ganymed", NULL);
}

/**
 * ganymed_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ganymed_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ganymed_proxy_new().
 *
 * Returns: (transfer full) (type GanymedProxy): The constructed proxy object or %NULL if @error is set.
 */
Ganymed *
ganymed_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GANYMED (ret);
  else
    return NULL;
}

/**
 * ganymed_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ganymed_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GanymedProxy): The constructed proxy object or %NULL if @error is set.
 */
Ganymed *
ganymed_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_GANYMED_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.manuel.Ganymed", NULL);
  if (ret != NULL)
    return GANYMED (ret);
  else
    return NULL;
}


/**
 * ganymed_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like ganymed_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ganymed_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See ganymed_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
ganymed_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_GANYMED_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.manuel.Ganymed", NULL);
}

/**
 * ganymed_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ganymed_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ganymed_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GanymedProxy): The constructed proxy object or %NULL if @error is set.
 */
Ganymed *
ganymed_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GANYMED (ret);
  else
    return NULL;
}

/**
 * ganymed_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like ganymed_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ganymed_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GanymedProxy): The constructed proxy object or %NULL if @error is set.
 */
Ganymed *
ganymed_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_GANYMED_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.manuel.Ganymed", NULL);
  if (ret != NULL)
    return GANYMED (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GanymedSkeleton:
 *
 * The #GanymedSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GanymedSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GanymedSkeleton.
 */

struct _GanymedSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_ganymed_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GanymedSkeleton *skeleton = GANYMED_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_GANYMED);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_GANYMED);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_ganymed_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GanymedSkeleton *skeleton = GANYMED_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ganymed_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_ganymed_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GanymedSkeleton *skeleton = GANYMED_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ganymed_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _ganymed_skeleton_vtable =
{
  _ganymed_skeleton_handle_method_call,
  _ganymed_skeleton_handle_get_property,
  _ganymed_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
ganymed_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return ganymed_interface_info ();
}

static GDBusInterfaceVTable *
ganymed_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_ganymed_skeleton_vtable;
}

static GVariant *
ganymed_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GanymedSkeleton *skeleton = GANYMED_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_ganymed_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _ganymed_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _ganymed_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _ganymed_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.manuel.Ganymed", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
ganymed_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void ganymed_skeleton_iface_init (GanymedIface *iface);
G_DEFINE_TYPE_WITH_CODE (GanymedSkeleton, ganymed_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_GANYMED, ganymed_skeleton_iface_init));

static void
ganymed_skeleton_finalize (GObject *object)
{
  GanymedSkeleton *skeleton = GANYMED_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (ganymed_skeleton_parent_class)->finalize (object);
}

static void
ganymed_skeleton_init (GanymedSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_GANYMED_SKELETON, GanymedSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
ganymed_skeleton_class_init (GanymedSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (GanymedSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = ganymed_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = ganymed_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = ganymed_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = ganymed_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = ganymed_skeleton_dbus_interface_get_vtable;
}

static void
ganymed_skeleton_iface_init (GanymedIface *iface)
{
}

/**
 * ganymed_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-manuel-Ganymed.top_of_page">org.manuel.Ganymed</link>.
 *
 * Returns: (transfer full) (type GanymedSkeleton): The skeleton object.
 */
Ganymed *
ganymed_skeleton_new (void)
{
  return GANYMED (g_object_new (TYPE_GANYMED_SKELETON, NULL));
}

