/*
 * Generated by gdbus-codegen 2.32.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "network-bindings.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.manuel.LunaDHT
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:LunaDHT
 * @title: LunaDHT
 * @short_description: Generated C code for the org.manuel.LunaDHT D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.manuel.LunaDHT ---- */

static const _ExtendedGDBusArgInfo _luna_dht_method_info_join_IN_ARG_host =
{
  {
    -1,
    "host",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_join_IN_ARG_port =
{
  {
    -1,
    "port",
    "q",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _luna_dht_method_info_join_IN_ARG_pointers[] =
{
  &_luna_dht_method_info_join_IN_ARG_host,
  &_luna_dht_method_info_join_IN_ARG_port,
  NULL
};

static const _ExtendedGDBusMethodInfo _luna_dht_method_info_join =
{
  {
    -1,
    "join",
    (GDBusArgInfo **) &_luna_dht_method_info_join_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-join",
  FALSE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_get_IN_ARG_app_id =
{
  {
    -1,
    "app_id",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_get_IN_ARG_key =
{
  {
    -1,
    "key",
    "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo * const _luna_dht_method_info_get_IN_ARG_pointers[] =
{
  &_luna_dht_method_info_get_IN_ARG_app_id,
  &_luna_dht_method_info_get_IN_ARG_key,
  NULL
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_get_OUT_ARG_results =
{
  {
    -1,
    "results",
    "aay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo * const _luna_dht_method_info_get_OUT_ARG_pointers[] =
{
  &_luna_dht_method_info_get_OUT_ARG_results,
  NULL
};

static const _ExtendedGDBusMethodInfo _luna_dht_method_info_get =
{
  {
    -1,
    "get",
    (GDBusArgInfo **) &_luna_dht_method_info_get_IN_ARG_pointers,
    (GDBusArgInfo **) &_luna_dht_method_info_get_OUT_ARG_pointers,
    NULL
  },
  "handle-get",
  FALSE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_put_IN_ARG_app_id =
{
  {
    -1,
    "app_id",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_put_IN_ARG_key =
{
  {
    -1,
    "key",
    "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_put_IN_ARG_value =
{
  {
    -1,
    "value",
    "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo _luna_dht_method_info_put_IN_ARG_ttl =
{
  {
    -1,
    "ttl",
    "x",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _luna_dht_method_info_put_IN_ARG_pointers[] =
{
  &_luna_dht_method_info_put_IN_ARG_app_id,
  &_luna_dht_method_info_put_IN_ARG_key,
  &_luna_dht_method_info_put_IN_ARG_value,
  &_luna_dht_method_info_put_IN_ARG_ttl,
  NULL
};

static const _ExtendedGDBusMethodInfo _luna_dht_method_info_put =
{
  {
    -1,
    "put",
    (GDBusArgInfo **) &_luna_dht_method_info_put_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-put",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _luna_dht_method_info_pointers[] =
{
  &_luna_dht_method_info_join,
  &_luna_dht_method_info_get,
  &_luna_dht_method_info_put,
  NULL
};

static const _ExtendedGDBusPropertyInfo _luna_dht_property_info_joined =
{
  {
    -1,
    "joined",
    "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "joined",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _luna_dht_property_info_pointers[] =
{
  &_luna_dht_property_info_joined,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _luna_dht_interface_info =
{
  {
    -1,
    "org.manuel.LunaDHT",
    (GDBusMethodInfo **) &_luna_dht_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_luna_dht_property_info_pointers,
    NULL
  },
  "luna-dht",
};


/**
 * luna_dht_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
luna_dht_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_luna_dht_interface_info;
}

/**
 * luna_dht_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #LunaDHT interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
luna_dht_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "joined");
  return property_id_begin - 1;
}



/**
 * LunaDHT:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link>.
 */

/**
 * LunaDHTIface:
 * @parent_iface: The parent interface.
 * @handle_get: Handler for the #LunaDHT::handle-get signal.
 * @handle_join: Handler for the #LunaDHT::handle-join signal.
 * @handle_put: Handler for the #LunaDHT::handle-put signal.
 * @get_joined: Getter for the #LunaDHT:joined property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link>.
 */

static void
luna_dht_default_init (LunaDHTIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * LunaDHT::handle-join:
   * @object: A #LunaDHT.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_host: Argument passed by remote caller.
   * @arg_port: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-manuel-LunaDHT.join">join()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call luna_dht_complete_join() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-join",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LunaDHTIface, handle_join),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_UINT);

  /**
   * LunaDHT::handle-get:
   * @object: A #LunaDHT.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_app_id: Argument passed by remote caller.
   * @arg_key: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-manuel-LunaDHT.get">get()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call luna_dht_complete_get() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LunaDHTIface, handle_get),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_VARIANT);

  /**
   * LunaDHT::handle-put:
   * @object: A #LunaDHT.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_app_id: Argument passed by remote caller.
   * @arg_key: Argument passed by remote caller.
   * @arg_value: Argument passed by remote caller.
   * @arg_ttl: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-manuel-LunaDHT.put">put()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call luna_dht_complete_put() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-put",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LunaDHTIface, handle_put),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_VARIANT, G_TYPE_VARIANT, G_TYPE_INT64);

  /* GObject properties for D-Bus properties: */
  /**
   * LunaDHT:joined:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-manuel-LunaDHT.joined">"joined"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("joined", "joined", "joined", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

typedef LunaDHTIface LunaDHTInterface;
G_DEFINE_INTERFACE (LunaDHT, luna_dht, G_TYPE_OBJECT);

/**
 * luna_dht_get_joined: (skip)
 * @object: A #LunaDHT.
 *
 * Gets the value of the <link linkend="gdbus-property-org-manuel-LunaDHT.joined">"joined"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
luna_dht_get_joined (LunaDHT *object)
{
  return LUNA_DHT_GET_IFACE (object)->get_joined (object);
}

/**
 * luna_dht_set_joined: (skip)
 * @object: A #LunaDHT.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-manuel-LunaDHT.joined">"joined"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
luna_dht_set_joined (LunaDHT *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "joined", value, NULL);
}

/**
 * luna_dht_call_join:
 * @proxy: A #LunaDHTProxy.
 * @arg_host: Argument to pass with the method invocation.
 * @arg_port: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-manuel-LunaDHT.join">join()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call luna_dht_call_join_finish() to get the result of the operation.
 *
 * See luna_dht_call_join_sync() for the synchronous, blocking version of this method.
 */
void
luna_dht_call_join (
    LunaDHT *proxy,
    const gchar *arg_host,
    guint16 arg_port,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "join",
    g_variant_new ("(sq)",
                   arg_host,
                   arg_port),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * luna_dht_call_join_finish:
 * @proxy: A #LunaDHTProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to luna_dht_call_join().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with luna_dht_call_join().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
luna_dht_call_join_finish (
    LunaDHT *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * luna_dht_call_join_sync:
 * @proxy: A #LunaDHTProxy.
 * @arg_host: Argument to pass with the method invocation.
 * @arg_port: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-manuel-LunaDHT.join">join()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See luna_dht_call_join() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
luna_dht_call_join_sync (
    LunaDHT *proxy,
    const gchar *arg_host,
    guint16 arg_port,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "join",
    g_variant_new ("(sq)",
                   arg_host,
                   arg_port),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * luna_dht_call_get:
 * @proxy: A #LunaDHTProxy.
 * @arg_app_id: Argument to pass with the method invocation.
 * @arg_key: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-manuel-LunaDHT.get">get()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call luna_dht_call_get_finish() to get the result of the operation.
 *
 * See luna_dht_call_get_sync() for the synchronous, blocking version of this method.
 */
void
luna_dht_call_get (
    LunaDHT *proxy,
    guint arg_app_id,
    GVariant *arg_key,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "get",
    g_variant_new ("(u@ay)",
                   arg_app_id,
                   arg_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * luna_dht_call_get_finish:
 * @proxy: A #LunaDHTProxy.
 * @out_results: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to luna_dht_call_get().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with luna_dht_call_get().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
luna_dht_call_get_finish (
    LunaDHT *proxy,
    GVariant **out_results,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aay)",
                 out_results);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * luna_dht_call_get_sync:
 * @proxy: A #LunaDHTProxy.
 * @arg_app_id: Argument to pass with the method invocation.
 * @arg_key: Argument to pass with the method invocation.
 * @out_results: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-manuel-LunaDHT.get">get()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See luna_dht_call_get() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
luna_dht_call_get_sync (
    LunaDHT *proxy,
    guint arg_app_id,
    GVariant *arg_key,
    GVariant **out_results,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "get",
    g_variant_new ("(u@ay)",
                   arg_app_id,
                   arg_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aay)",
                 out_results);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * luna_dht_call_put:
 * @proxy: A #LunaDHTProxy.
 * @arg_app_id: Argument to pass with the method invocation.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_value: Argument to pass with the method invocation.
 * @arg_ttl: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-manuel-LunaDHT.put">put()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call luna_dht_call_put_finish() to get the result of the operation.
 *
 * See luna_dht_call_put_sync() for the synchronous, blocking version of this method.
 */
void
luna_dht_call_put (
    LunaDHT *proxy,
    guint arg_app_id,
    GVariant *arg_key,
    GVariant *arg_value,
    gint64 arg_ttl,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "put",
    g_variant_new ("(u@ay@ayx)",
                   arg_app_id,
                   arg_key,
                   arg_value,
                   arg_ttl),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * luna_dht_call_put_finish:
 * @proxy: A #LunaDHTProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to luna_dht_call_put().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with luna_dht_call_put().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
luna_dht_call_put_finish (
    LunaDHT *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * luna_dht_call_put_sync:
 * @proxy: A #LunaDHTProxy.
 * @arg_app_id: Argument to pass with the method invocation.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_value: Argument to pass with the method invocation.
 * @arg_ttl: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-manuel-LunaDHT.put">put()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See luna_dht_call_put() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
luna_dht_call_put_sync (
    LunaDHT *proxy,
    guint arg_app_id,
    GVariant *arg_key,
    GVariant *arg_value,
    gint64 arg_ttl,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "put",
    g_variant_new ("(u@ay@ayx)",
                   arg_app_id,
                   arg_key,
                   arg_value,
                   arg_ttl),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * luna_dht_complete_join:
 * @object: A #LunaDHT.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-manuel-LunaDHT.join">join()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
luna_dht_complete_join (
    LunaDHT *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * luna_dht_complete_get:
 * @object: A #LunaDHT.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @results: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-manuel-LunaDHT.get">get()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
luna_dht_complete_get (
    LunaDHT *object,
    GDBusMethodInvocation *invocation,
    GVariant *results)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@aay)",
                   results));
}

/**
 * luna_dht_complete_put:
 * @object: A #LunaDHT.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-manuel-LunaDHT.put">put()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
luna_dht_complete_put (
    LunaDHT *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * LunaDHTProxy:
 *
 * The #LunaDHTProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * LunaDHTProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #LunaDHTProxy.
 */

struct _LunaDHTProxyPrivate
{
  GData *qdata;
};

static void luna_dht_proxy_iface_init (LunaDHTIface *iface);

G_DEFINE_TYPE_WITH_CODE (LunaDHTProxy, luna_dht_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_LUNA_DHT, luna_dht_proxy_iface_init));

static void
luna_dht_proxy_finalize (GObject *object)
{
  LunaDHTProxy *proxy = LUNA_DHT_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (luna_dht_proxy_parent_class)->finalize (object);
}

static void
luna_dht_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _luna_dht_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
luna_dht_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property `%s' on interface org.manuel.LunaDHT: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
luna_dht_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _luna_dht_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.manuel.LunaDHT", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) luna_dht_proxy_set_property_cb, (gpointer) info);
  g_variant_unref (variant);
}

static void
luna_dht_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_luna_dht_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_LUNA_DHT);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_LUNA_DHT);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
luna_dht_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  LunaDHTProxy *proxy = LUNA_DHT_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_luna_dht_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_luna_dht_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
luna_dht_proxy_get_joined (LunaDHT *object)
{
  LunaDHTProxy *proxy = LUNA_DHT_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "joined");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
luna_dht_proxy_init (LunaDHTProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_LUNA_DHT_PROXY, LunaDHTProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), luna_dht_interface_info ());
}

static void
luna_dht_proxy_class_init (LunaDHTProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (LunaDHTProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = luna_dht_proxy_finalize;
  gobject_class->get_property = luna_dht_proxy_get_property;
  gobject_class->set_property = luna_dht_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = luna_dht_proxy_g_signal;
  proxy_class->g_properties_changed = luna_dht_proxy_g_properties_changed;


  luna_dht_override_properties (gobject_class, 1);
}

static void
luna_dht_proxy_iface_init (LunaDHTIface *iface)
{
  iface->get_joined = luna_dht_proxy_get_joined;
}

/**
 * luna_dht_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call luna_dht_proxy_new_finish() to get the result of the operation.
 *
 * See luna_dht_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
luna_dht_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_LUNA_DHT_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.manuel.LunaDHT", NULL);
}

/**
 * luna_dht_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to luna_dht_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with luna_dht_proxy_new().
 *
 * Returns: (transfer full) (type LunaDHTProxy): The constructed proxy object or %NULL if @error is set.
 */
LunaDHT *
luna_dht_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return LUNA_DHT (ret);
  else
    return NULL;
}

/**
 * luna_dht_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See luna_dht_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type LunaDHTProxy): The constructed proxy object or %NULL if @error is set.
 */
LunaDHT *
luna_dht_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_LUNA_DHT_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.manuel.LunaDHT", NULL);
  if (ret != NULL)
    return LUNA_DHT (ret);
  else
    return NULL;
}


/**
 * luna_dht_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like luna_dht_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call luna_dht_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See luna_dht_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
luna_dht_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_LUNA_DHT_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.manuel.LunaDHT", NULL);
}

/**
 * luna_dht_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to luna_dht_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with luna_dht_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type LunaDHTProxy): The constructed proxy object or %NULL if @error is set.
 */
LunaDHT *
luna_dht_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return LUNA_DHT (ret);
  else
    return NULL;
}

/**
 * luna_dht_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like luna_dht_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See luna_dht_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type LunaDHTProxy): The constructed proxy object or %NULL if @error is set.
 */
LunaDHT *
luna_dht_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_LUNA_DHT_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.manuel.LunaDHT", NULL);
  if (ret != NULL)
    return LUNA_DHT (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * LunaDHTSkeleton:
 *
 * The #LunaDHTSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * LunaDHTSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #LunaDHTSkeleton.
 */

struct _LunaDHTSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_luna_dht_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_LUNA_DHT);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_LUNA_DHT);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_luna_dht_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_luna_dht_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_luna_dht_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_luna_dht_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _luna_dht_skeleton_vtable =
{
  _luna_dht_skeleton_handle_method_call,
  _luna_dht_skeleton_handle_get_property,
  _luna_dht_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
luna_dht_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return luna_dht_interface_info ();
}

static GDBusInterfaceVTable *
luna_dht_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_luna_dht_skeleton_vtable;
}

static GVariant *
luna_dht_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_luna_dht_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _luna_dht_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _luna_dht_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _luna_dht_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.manuel.LunaDHT", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _luna_dht_emit_changed (gpointer user_data);

static void
luna_dht_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _luna_dht_emit_changed (skeleton);
}

static void luna_dht_skeleton_iface_init (LunaDHTIface *iface);
G_DEFINE_TYPE_WITH_CODE (LunaDHTSkeleton, luna_dht_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_LUNA_DHT, luna_dht_skeleton_iface_init));

static void
luna_dht_skeleton_finalize (GObject *object)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (luna_dht_skeleton_parent_class)->finalize (object);
}

static void
luna_dht_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_luna_dht_emit_changed (gpointer user_data)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *l;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.manuel.LunaDHT",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (l = connections; l != NULL; l = l->next)
        {
          GDBusConnection *connection = l->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_luna_dht_schedule_emit_changed (LunaDHTSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
luna_dht_skeleton_notify (GObject      *object,
  GParamSpec *pspec)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _luna_dht_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
luna_dht_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _luna_dht_schedule_emit_changed (skeleton, _luna_dht_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
luna_dht_skeleton_init (LunaDHTSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_LUNA_DHT_SKELETON, LunaDHTSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_BOOLEAN);
}

static gboolean 
luna_dht_skeleton_get_joined (LunaDHT *object)
{
  LunaDHTSkeleton *skeleton = LUNA_DHT_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
luna_dht_skeleton_class_init (LunaDHTSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (LunaDHTSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = luna_dht_skeleton_finalize;
  gobject_class->get_property = luna_dht_skeleton_get_property;
  gobject_class->set_property = luna_dht_skeleton_set_property;
  gobject_class->notify       = luna_dht_skeleton_notify;


  luna_dht_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = luna_dht_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = luna_dht_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = luna_dht_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = luna_dht_skeleton_dbus_interface_get_vtable;
}

static void
luna_dht_skeleton_iface_init (LunaDHTIface *iface)
{
  iface->get_joined = luna_dht_skeleton_get_joined;
}

/**
 * luna_dht_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-manuel-LunaDHT.top_of_page">org.manuel.LunaDHT</link>.
 *
 * Returns: (transfer full) (type LunaDHTSkeleton): The skeleton object.
 */
LunaDHT *
luna_dht_skeleton_new (void)
{
  return LUNA_DHT (g_object_new (TYPE_LUNA_DHT_SKELETON, NULL));
}

